INSERT INTO tb_category (name, url, created_at) VALUES ('Medicamentos', 'farmacia.com.br/medicamentos', NOW());
INSERT INTO tb_category (name, url, created_at) VALUES ('Vitaminas e Suplementos', 'farmacia.com.br/vitaminas', NOW());
INSERT INTO tb_category (name, url, created_at) VALUES ('Beleza e Perfumaria', 'farmacia.com.br/beleza', NOW());
INSERT INTO tb_category (name, url, created_at) VALUES ('Higiene e Cuidados Pessoais', 'farmacia.com.br/higiene', NOW());
INSERT INTO tb_category (name, url, created_at) VALUES ('Bebês e Crianças', 'farmacia.com.br/bebes', NOW());
INSERT INTO tb_category (name, url, created_at) VALUES ('Primeiros Socorros', 'farmacia.com.br/primeiros-socorros', NOW());
INSERT INTO tb_category (name, url, created_at) VALUES ('Artigos Médicos', 'farmacia.com.br/artigos-medicos', NOW());
INSERT INTO tb_category (name, url, created_at) VALUES ('Dermocosméticos', 'farmacia.com.br/dermocosmeticos', NOW());
INSERT INTO tb_category (name, url, created_at) VALUES ('Aparelhos de Saúde', 'farmacia.com.br/aparelhos-saude', NOW());
INSERT INTO tb_category (name, url, created_at) VALUES ('Alimentos Saudáveis', 'farmacia.com.br/alimentos-saudaveis', NOW());

INSERT INTO tb_product (name, description, price, img_Url, url, created_at) VALUES ('Dipirona Monoidratada 500mg', 'Comprimido para alívio de dor e febre.', 7.99, 'dipirona.jpg', 'farmacia.com.br/dipirona', NOW());
INSERT INTO tb_product (name, description, price, img_Url, url, created_at) VALUES ('Vitamina C 1000mg', 'Cápsula para fortalecimento do sistema imunológico.', 19.99, 'vitaminaC.jpg', 'farmacia.com.br/vitaminaC', NOW());
INSERT INTO tb_product (name, description, price, img_Url, url, created_at) VALUES ('Shampoo Anticaspa 200ml', 'Limpeza e combate à caspa.', 24.99, 'shampooAnticaspa.jpg', 'farmacia.com.br/shampooAnticaspa', NOW());
INSERT INTO tb_product (name, description, price, img_Url, url, created_at) VALUES ('Protetor Solar FPS 50', 'Proteção solar para todos os tipos de pele.', 49.99, 'protetorSolar.jpg', 'farmacia.com.br/protetorSolar', NOW());
INSERT INTO tb_product (name, description, price, img_Url, url, created_at) VALUES ('Termômetro Digital', 'Termômetro para medição de temperatura corporal.', 29.99, 'termometro.jpg', 'farmacia.com.br/termometro', NOW());
INSERT INTO tb_product (name, description, price, img_Url, url, created_at) VALUES ('Creme Dental 90g', 'Creme dental para higiene bucal diária.', 5.99, 'cremeDental.jpg', 'farmacia.com.br/cremeDental', NOW());
INSERT INTO tb_product (name, description, price, img_Url, url, created_at) VALUES ('Escova Dental', 'Escova dental macia para uso diário.', 3.99, 'escovaDental.jpg', 'farmacia.com.br/escovaDental', NOW());
INSERT INTO tb_product (name, description, price, img_Url, url, created_at) VALUES ('Álcool Gel 70\%', 'Álcool gel para higienização das mãos.', 9.99, 'alcoolGel.jpg', 'farmacia.com.br/alcoolGel', NOW());
INSERT INTO tb_product (name, description, price, img_Url, url, created_at) VALUES ('Band-Aid', 'Curativo adesivo para pequenos ferimentos.', 4.99, 'bandAid.jpg', 'farmacia.com.br/bandAid', NOW());
INSERT INTO tb_product (name, description, price, img_Url, url, created_at) VALUES ('Antisséptico Bucal 250ml', 'Enxaguante bucal para higiene oral.', 14.99, 'antissepticoBucal.jpg', 'farmacia.com.br/antissepticoBucal', NOW());
INSERT INTO tb_product (name, description, price, img_Url, url, created_at) VALUES ('Sabonete Líquido 200ml', 'Sabonete líquido para limpeza das mãos.', 7.99, 'saboneteLiquido.jpg', 'farmacia.com.br/saboneteLiquido', NOW());
INSERT INTO tb_product (name, description, price, img_Url, url, created_at) VALUES ('Desodorante Aerosol 150ml', 'Desodorante aerosol para proteção diária.', 12.99, 'desodorante.jpg', 'farmacia.com.br/desodorante', NOW());
INSERT INTO tb_product (name, description, price, img_Url, url, created_at) VALUES ('Lenços Umedecidos', 'Lenços umedecidos para limpeza e higiene.', 8.99, 'lencosUmedecidos.jpg', 'farmacia.com.br/lencosUmedecidos', NOW());
INSERT INTO tb_product (name, description, price, img_Url, url, created_at) VALUES ('Fralda Geriátrica', 'Fralda geriátrica para incontinência.', 39.99, 'fraldaGeriatrica.jpg', 'farmacia.com.br/fraldaGeriatrica', NOW());
INSERT INTO tb_product (name, description, price, img_Url, url, created_at) VALUES ('Soro Fisiológico 500ml', 'Soro fisiológico para hidratação nasal.', 6.99, 'soroFisiologico.jpg', 'farmacia.com.br/soroFisiologico', NOW());
INSERT INTO tb_product (name, description, price, img_Url, url, created_at) VALUES ('Gaze Estéril', 'Gaze estéril para curativos.', 2.99, 'gazeEsteril.jpg', 'farmacia.com.br/gazeEsteril', NOW());
INSERT INTO tb_product (name, description, price, img_Url, url, created_at) VALUES ('Esparadrapo 10m', 'Esparadrapo para fixação de curativos.', 3.99, 'esparadrapo.jpg', 'farmacia.com.br/esparadrapo', NOW());
INSERT INTO tb_product (name, description, price, img_Url, url, created_at) VALUES ('Pomada para Assaduras', 'Pomada para prevenção de assaduras.', 14.99, 'pomadaAssaduras.jpg', 'farmacia.com.br/pomadaAssaduras', NOW());
INSERT INTO tb_product (name, description, price, img_Url, url, created_at) VALUES ('Creme Hidratante 200ml', 'Creme hidratante para pele seca.', 19.99, 'cremeHidratante.jpg', 'farmacia.com.br/cremeHidratante', NOW());
INSERT INTO tb_product (name, description, price, img_Url, url, created_at) VALUES ('Repelente de Insetos 100ml', 'Repelente de insetos para uso corporal.', 15.99, 'repelente.jpg', 'farmacia.com.br/repelente', NOW());
INSERT INTO tb_product (name, description, price, img_Url, url, created_at) VALUES ('Colírio 15ml', 'Colírio para alívio de irritações oculares.', 9.99, 'colirio.jpg', 'farmacia.com.br/colirio', NOW());
INSERT INTO tb_product (name, description, price, img_Url, url, created_at) VALUES ('Luva Descartável', 'Luva descartável para procedimentos.', 12.99, 'luvaDescartavel.jpg', 'farmacia.com.br/luvaDescartavel', NOW());
INSERT INTO tb_product (name, description, price, img_Url, url, created_at) VALUES ('Máscara Cirúrgica', 'Máscara cirúrgica para proteção.', 19.99, 'mascaraCirurgica.jpg', 'farmacia.com.br/mascaraCirurgica', NOW());
INSERT INTO tb_product (name, description, price, img_Url, url, created_at) VALUES ('Termômetro Infravermelho', 'Termômetro infravermelho para medição de temperatura.', 89.99, 'termometroInfravermelho.jpg', 'farmacia.com.br/termometroInfravermelho', NOW());
INSERT INTO tb_product (name, description, price, img_Url, url, created_at) VALUES ('Oxímetro de Pulso', 'Oxímetro para medição de saturação de oxigênio.', 59.99, 'oximetro.jpg', 'farmacia.com.br/oximetro', NOW());
INSERT INTO tb_product (name, description, price, img_Url, url, created_at) VALUES ('Nebulizador', 'Nebulizador para tratamento respiratório.', 129.99, 'nebulizador.jpg', 'farmacia.com.br/nebulizador', NOW());
INSERT INTO tb_product (name, description, price, img_Url, url, created_at) VALUES ('Balança Digital', 'Balança digital para medição de peso corporal.', 49.99, 'balancaDigital.jpg', 'farmacia.com.br/balancaDigital', NOW());
INSERT INTO tb_product (name, description, price, img_Url, url, created_at) VALUES ('Cadeira de Rodas', 'Cadeira de rodas para mobilidade.', 499.99, 'cadeiraRodas.jpg', 'farmacia.com.br/cadeiraRodas', NOW());


INSERT INTO tb_product_category (product_id, category_id) VALUES (1, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (2, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (3, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (4, 4);
INSERT INTO tb_product_category (product_id, category_id) VALUES (5, 5);
INSERT INTO tb_product_category (product_id, category_id) VALUES (6, 6);
INSERT INTO tb_product_category (product_id, category_id) VALUES (7, 7);
INSERT INTO tb_product_category (product_id, category_id) VALUES (8, 8);
INSERT INTO tb_product_category (product_id, category_id) VALUES (9, 9);
INSERT INTO tb_product_category (product_id, category_id) VALUES (10, 10);
INSERT INTO tb_product_category (product_id, category_id) VALUES (11, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (12, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (13, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (14, 4);
INSERT INTO tb_product_category (product_id, category_id) VALUES (15, 5);
INSERT INTO tb_product_category (product_id, category_id) VALUES (16, 6);
INSERT INTO tb_product_category (product_id, category_id) VALUES (17, 7);
INSERT INTO tb_product_category (product_id, category_id) VALUES (18, 8);
INSERT INTO tb_product_category (product_id, category_id) VALUES (19, 9);
INSERT INTO tb_product_category (product_id, category_id) VALUES (20, 10);
INSERT INTO tb_product_category (product_id, category_id) VALUES (21, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (22, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (23, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (24, 4);
INSERT INTO tb_product_category (product_id, category_id) VALUES (25, 5);